### ISSUE TITLE
Documentation on "Generate transfer code" missing (Ver. 2.0.0)

### ISSUE THREAD

**Issue by r-r-liu** [admin-ch/CovidCertificate-App-iOS#114]
I find no documentation in the built-in FAQ's in the app for "Generate transfer code", accessed by pressing + in the lower right corner.  What does this do?

**Comment by goebelUB** [comment]
Clicking *Generate transfer code* does not immediately generate a code - just like clicking "Scan QR code" or "Import PDF" has an additional confirmation prompt before importing a certificate.
If you click it, you get to another screen that has more details, including a dedicated FAQ for the transfer code feature.

**Comment by r-r-liu** [comment]
OK, thanks. It's generally not a good idea to click on buttons without some indication of what might happen.  Might I suggest adopting the convention that "..." in the label means there's more to the dialog, i.e., I can cancel out, whereas no "..." means that the app will perform an action when I click the button?

**Comment by goebelUB** [comment]
I passed your feedback on to the design team.
In addition there is now an entry in the main FAQ that gives a short explanation of the transfer codes feature (*"What is a transfer code?"*). The main bulk explaining it in more detail remains in the other FAQ in the dedicated screen.
