### ISSUE TITLE
Transfer Code Expiry too short

### ISSUE THREAD

**Issue by mopenmind** [admin-ch/CovidCertificate-App-iOS#139]
Transfer codes expire after 7 days. It seems that local authorities are not able to meet this timeline. Would it me feasible to extend the expiry to 14 days until the processes have been established?

**Comment by goebelUB** [comment]
Could you please elaborate on your exact use case?
E.g. Is it about a test, vaccination or recovery certificate? E.g. PCR certificates are only valid 3 days anway - did you have to submit the transfer code 7 days before the actual test? Any other details that are relevant in your situation?
