### ISSUE TITLE
Feature request: Copy transfer code to clipboard

### ISSUE THREAD

**Issue by samuelwaeny** [admin-ch/CovidCertificate-App-iOS#143]
As some systems allow providing a transfercode when registering for a COVID-test, it would help for the following reasons;
also the time to implement should be minimal.

- Prevent the user from switching back and forth to validate the code when manually copying (between app and registation form when doing it on the same device)
- Prevent failed registation attempts (in cases where the transfercode wasn't copied correctly)
- With shared clipboards this could even help if the registration does not happen on the same device

**Comment by goebelUB** [comment]
See #141

**Comment by goebelUB** [comment]
This is in v2.2.0 for iOS which is now out.
