### ISSUE TITLE
[COVID Certificate Check App]: Suggestion to omit need to click «verify» after switching to app

### ISSUE THREAD

**Issue by sprain** [admin-ch/CovidCertificate-App-iOS#169]
The **current behaviour** of the COVID Certificate Check App on iOS is as follows:

1. Open the `COVID Certificate Check` app
2. Click «verify»
3. Verify certificates
4. Switch to a different app (for example to check some other related information)
5. Switch back to the `COVID Certificate Check` app
6. You need to start over at step 2 and click «verify» again

In cases where you often have to switch between apps, this extra click quickly feels inefficent and unnecessary. 

**Suggestion for improvement:**

It would be nice if after switching back to the app, one could immediately be at step 3 and verify the next certificate right away.

**Comment by UBaggeler** [comment]
Dear @sprain  

Thank you for your suggestion. The necessary changes have been implemented and are being rolled-out currently (version 2.6.0 in the AppStore). Feel free to re-open this issue if it does not work as intended.

Thanks,
Fabian
