### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by comache** [admin-ch/CovidCertificate-App-iOS#183]
I am trying to localize the app in another language not provided by the default code.
Added new localized strings but How It Works page seems that is not using info from localized documents and keep appearing in english.
How can I translated it too?

**Comment by comache** [comment]
Nobody?

**Comment by goebelUB** [comment]
I think the FAQs, How It Works, etc are also loaded from the backend. The copy in the app is only a fallback in case you were never connected to the internet and no local version was cached.

So you'd need to disable this in your fork, at the cost of no longer being able to push out new FAQs without an app update.
