### ISSUE TITLE
Remove the Refresh/Green Checkmark validity indication

### ISSUE THREAD

**Issue by ibauersachs** [admin-ch/CovidCertificate-App-iOS#184]
Restaurants, fitness centers, etc. use the green checkmark after the refresh to trust the validity of the certificate instead of scanning the QR code. This is insecure however: every "schwurbler" can simply clone this repository and slightly modify the app to always show a green checkmark, regardless of what is shown in the QR code and enter an otherwise off-limit area.

**Comment by denysvitali** [comment]
FYI, this is my proposal for Android:
https://github.com/admin-ch/CovidCertificate-App-Android/pull/336

**Comment by ibauersachs** [comment]
As per the discussion in the Android app, this seems to work as intended.
https://github.com/admin-ch/CovidCertificate-App-Android/issues/295#issuecomment-999036793
