### ISSUE TITLE
Limit number of imported certificates, warn users

### ISSUE THREAD

**Issue by chrisleduc** [admin-ch/CovidCertificate-App-iOS#185]
I have noticed that venues are using the Covid Certificate app instead of Covid Check. 

The app should not allow more than e.g. 10 or 20 certificate. Additionally, it should warn users adding more than three:
"This app should not be used to verify certificates. You should only scan your own certificates. Please use Covid Check instead to verify your guests certificates".

**Comment by goebelUB** [comment]
Thanks for your feedback, it raises a good point.

Meanwhile as a user, you can use the certificate light, which cannot be imported into CovidCert.

**Comment by goebelUB** [comment]
Version 2.8.0 will warn the user with a pop-up when they scan too many certificates in a too short time period and inform them that they should use the Covid Check app instead. Note we count *all scanned* certificates, independent of whether they were *imported* or not (to also cover misuse of the *Scan Again* button). However, we decided against a hard import limit.
