### ISSUE TITLE
Correct Display the Booster Vaccination not as Incomplete

### ISSUE THREAD

**Issue by ojehle** [admin-ch/CovidCertificate-App-iOS#247]
Swiss Covid App shows Booster Vaccinations as Incomplete Vaccinations
in my certificate i have 3 doses of a total of 2 needed.

I expect the same on the android version

diff --git a/Wallet/Screens/Certificates/CertificateDetailView.swift b/Wallet/Screens/Certificates/CertificateDetailView.swift
index ebfb2d9..4c89e1d 100644
--- a/Wallet/Screens/Certificates/CertificateDetailView.swift
+++ b/Wallet/Screens/Certificates/CertificateDetailView.swift
@@ -81,7 +81,7 @@ class CertificateDetailView: UIView {
 
         addDividerLine()
 
-        if vaccinations.allSatisfy({ $0.doseNumber == $0.totalDoses }) {
+        if vaccinations.allSatisfy({ $0.doseNumber >= $0.totalDoses }) {
             addTitle(title: UBLocalized.translationWithEnglish(key: .covid_certificate_vaccination_title_key))
         } else {
             addTitle(title: UBLocalized.translationWithEnglish(key: .wallet_certificate_type_incomplete_vaccine_key))
diff --git a/Wallet/Screens/Certificates/CertificateDetailViewController.swift b/Wallet/Screens/Certificates/CertificateDetailViewController.swift
index 2035dcf..4df70b5 100644
--- a/Wallet/Screens/Certificates/CertificateDetailViewController.swift
+++ b/Wallet/Screens/Certificates/CertificateDetailViewController.swift
@@ -247,7 +247,7 @@ class CertificateDetailViewController: ViewController {
         case let .success(holder):
             guard let certificate = holder.certificate as? DCCCert else { break }
             let vaccinations = certificate.vaccinations ?? []
-            if !vaccinations.allSatisfy({ $0.doseNumber == $0.totalDoses }) {
+            if !vaccinations.allSatisfy({ $0.doseNumber >= $0.totalDoses }) {
                 title = UBLocalized.wallet_certificate_evidence_title.uppercased()
             }
         case .failure:

**Comment by ojehle** [comment]
not shure if doseNumber and totalDoses must be switched equal or less ..... but anyway.. it looks like the booster makes the number of doses applied higher, but the fixed number 2 (for moderna/pfizer) will stay on the certificate.  in my case 3/2.

**Comment by goebelUB** [comment]
Thanks for reporting! This seems to be a UI issue in the wallet. Even though we show the wrong strings (e.g. the title "Vaccination incomplete"), the certificate itself should still be shown as valid (blue box with "Only valid with an identity document").

Could you please check that your cert is also shown green in the verifier ([Covid Check](https://apps.apple.com/us/app/covid-certificate/id1565917510))?

On a side note: as far as I know booster certs should be issued as 3/3. Is this a Swiss certificate?

**Comment by ojehle** [comment]
It's a certificate from liechtenstein...  

It's valid in both apps.

the certificate is valid - green  with the check app.  
and valid with document in the blue app.

but i think it's still correct the information in the certificate. because for moderna you need 2 doses that it's valid. the booster is recommended, but not a must. 

I was not sure if the totalDoses or doseNumber is the "must" have dose.. anyway.. if the amount of injections i got is higher then the one i must have, it should be not shown as "incomplete"...
