### ISSUE TITLE
Covid Check App - Add 2G rule Check

### ISSUE THREAD

**Issue by tecnovel** [admin-ch/CovidCertificate-App-iOS#253]
It would be really nice, to see if the checked covid certificate is corresponding to the 2G rule or not.

Now we have to check everytime the certificate itself and this is tedious work, which can be optimized.
In this way it would be much faster. And i think there will be many 2G checks soon.
I was looking in the API but you can't see this information yet.

**Comment by goebelUB** [comment]
Version 3.0.0 is being rolled out now and includes this feature.
