### ISSUE TITLE
info not shown completely

### ISSUE THREAD

**Issue by urs8000** [admin-ch/CovidCertificate-App-iOS#263]
at new 2G/3G the info is not shown completely.
a scrollbar is missing
![3DBEA14C-66D6-4FF4-AF0C-2B5B0663FD49](https://user-images.githubusercontent.com/6280368/145894027-ca0303f5-1623-449e-909a-bbba22e10959.jpeg)

**Comment by stmitt** [comment]
Thanks for your feedback. 
This issue was fixed with #262 and will be included in the next release.
