### ISSUE TITLE
Booster after Johnson&Johnson does not reset duration

### ISSUE THREAD

**Issue by HarriOrri** [admin-ch/CovidCertificate-App-iOS#271]
Hi,

getting a booster shot (in my case of Pfizer) after one dose of J&J single dose vaccine does not reset the duration to 1 year after the booster. However, a booster after 2 shots of AZ, Pfizer, Moderna and etc. giving a total of 3 shots does reset the duration to one year after the booster.

As far as I know, getting a booster shot in Switzerland resets the duration to 1 year after it, but I couldn't find anything about getting a booster shot after the J&J vaccine and the rules about the certificate duration.

The vaccination certificates which I used as reference (1x J&J and 1x Pfizer booster/2x AZ and 1x Moderna booster) are both from a foreign country but using the Covid Cert app. The J&J/Pfizer still has the duration as 365+21 days from the original dose of J&J while the AZ/Moderna has it now set as 364 days after the booster dose of Moderna.

**Comment by goebelUB** [comment]
First of all, just to clarify: the Swiss Covid Cert app considers each certificate separately. That is, it does not take the first (original) certificate into account when validating the second (booster) certificate.

Therefore the only thing that matters is what is stored in your booster certificate.

If you open the offending Pfizer booster certificate:

1. What does value does it say under "Dose" (e.g. 2/2)?
2. Is the "Date of Vaccination" correct, i.e. the date of the booster shot?
3. If you scroll through the entire certificate details page: does it only contain a single vaccination, i.e. the booster shot? Or does it contain multiple vaccinations (e.g. both the J&J and the Pfizer booster)?

**Comment by HarriOrri** [comment]
For the certificate with 1x J&J and 1x Pfizer booster:

1. It says 2/2 under "Dose"
2. The date of vaccination is the date of the J&J vaccination
3. All the details are set for the J&J vaccine (with the exception of 2/2 doses). The details are as follows:
- Dose: 2/2
- Disease or agent targeted: COVID-19
- Vaccine type: SARS-CoV-2 antigen vaccine
- Product: COVID-19 Vaccine Janssen
- Manufacturer: Janssen-Cilag International
- Date of vaccination: Date of original J&J shot

**Comment by goebelUB** [comment]
Right, I think the issue is that the "date of vaccination" contains the original J&J vaccination date, not the Pfizer booster date.
Because the "date of vaccination" is the only date that the app can go from (since it doesn't look at any other certificates), it calculates the validity time based on the J&J date.

I recommend you talk to the issuer of the certificate and ask them to correct that (by issuing a new certificate with the booster date set in the "date of vaccination" field).

**Comment by HarriOrri** [comment]
This was indeed a problem with the issuing of the foreign certificate. They have solved the problem and a new certificate shows the correct expiration date in the app.
