### ISSUE TITLE
2G+ verification mode

### ISSUE THREAD

**Issue by stapelberg** [admin-ch/CovidCertificate-App-iOS#283]
Currently, the Covid Check app only offers 2G or 3G verification modes.

Per https://www.watson.ch/schweiz/wirtschaft/802048735-2g-und-homeoffice-pflicht-das-hat-der-bundesrat-heute-beschlossen, we could upgrade to 2G+, but the Covid Check app does not currently show 2G+ in its UI at all — the results look identical for someone who was vaccinated in the last 4 months and someone who wasn’t.

**Comment by goebelUB** [comment]
This is included in version 3.1.0 that is being released today.
