### ISSUE TITLE
Authentication for opening the app

### ISSUE THREAD

**Issue by informatik-bks** [admin-ch/CovidCertificate-App-iOS#33]
Use fingerprint/biometric check to open the app, this helps to verify the owner of the cert.
As backup use code/password

**Comment by thebluepotato** [comment]
IMO verification of ownership is done by checking ID/Passport. Biometrics would however protect the sensitive personal data embedded in the certificate (including family members for instance). Is it realistic that a third party would look for the app and scan the code with the Verifier or is it enough to check that the phone had a passcode?

**Comment by thebluepotato** [comment]
IMO verification of ownership is done by checking ID/Passport. Biometrics would however protect the sensitive personal data embedded in the certificate (including family members for instance). Is it realistic that a third party would look for the app and scan the code with the Verifier or is it enough to check that the phone had a passcode?

**Comment by informatik-bks** [comment]
it was just an idea to make it more secure
