### ISSUE TITLE
Add new certificate from downloaded PDF certificate

### ISSUE THREAD

**Issue by wollmich** [admin-ch/CovidCertificate-App-iOS#70]
Yesterday I had my second vaccination and I received an SMS that I can download the COVID certificate as PDF from <https://be.vacme.ch/>. I've downloaded the PDF to my iPhone. As a next step I wanted to add this certificate into your app. I saw that this is not possible, because I can just use the camera to add a certificate. So I need to download it a again on **second device** and then use my iPhone to add the certificate to your app. Are you serious?

**Comment by goebelUB** [comment]
The upcoming release supports acting as a share target for PDFs. You will be able to share the PDF from any other app and select the COVID Certificate app to import your certificate.

The "opposite" direction (having an Import-from-PDF button in the app) is under review.

**Comment by goebelUB** [comment]
v2.0.0 includes the other direction (a button straight in the app) and is now being rolled out.
